### ISSUE TITLE
Simple bug fix

### ISSUE THREAD

**Issue by skunklem** [willros/bam2plot#1]
Hey, I was trying to use bam2plot and ran into two issues, both are simple fixes, but the first is extra important because the script won't even run, as it is right now.

1. `list[int]` throws an error because you can't index type objects. Instead, you need to 
  * import List via `from typing import List` and
  * edit line 109 to use List[int] like below:
   `def coverage_for_many_values(df: pd.DataFrame, values: List[int]) -> pd.DataFrame:`

2. If a bam file has regions with 0 coverage, Depth values become NaN, raising a KeyError when running `sns.lineplot(data=mpileup_df, x="Position", y="Depth")`. You may have reasons for wanting it as it is, but I feel like a program made to plot coverage should be able to account for missing depth values. You may want to do something like my solution:
* after creating mpileup_df, add the line `mpileup_df["Depth"] = mpileup_df["Depth"].fillna(0)` to fill missing Depth values as 0 so they can be plotted.

Here's a copy of your script with those two changes made
[main.py.txt](https://github.com/willros/bam2plot/files/12468026/main.py.txt)

Cheers,
Sam

**Comment by willros** [comment]
Hi,

1. Yes, you can do `list[int]` in python [see the docs](https://docs.python.org/3/library/typing.html)


If you want to suggest changes, I am happy to review PRs.

Thanks,
Ville

**Comment by skunklem** [comment]
I wonder if that's a python version thing. When I first ran it and had to make that typing/List edit, I was running python3.8. Now, I just tested it with python 3.11, and `list[int]` worked fine, as you said. You may want to increase the `python_requires` in your `setup.py`, if that's the case.

I'm not yet familiar with the pull request process. For two small complaints (one of which now being moot), I didn't think it worth the effort to learn today...

Best,
Sam
