### ISSUE TITLE
mean_coverage_total calculation

### ISSUE THREAD

**Issue by alvanuffelen** [willros/bam2plot#10]
https://github.com/willros/bam2plot/blob/65e6e4fe3bfa17255edbd49c04754c20c183a3e3/bam2plot/main.py#L102-L109

If I understood correctly, mean_coverage is the average coverage per reference and mean_coverage_total is the average coverage of all references. 
If this is correct, I think the calculation for the mean_coverage_total is not correct. You sum up the "total_bases" of each reference multiple times because there are multiple entries for each reference.
Should the sum of "total_bases" in each unique pair of ["ref", "total_bases"] not be used?

**Comment by willros** [comment]
You might be right. Please add a PR to show what you mean!
