### ISSUE TITLE
come across an error

### ISSUE THREAD

**Issue by jing-rstbio** [willros/bam2plot#2]
Hi,
I want to run bam2plot to plot my sequencing bam file. I can install it successfully, but when I run it, I came across an error:
 File "/home/jing/.local/lib/python3.8/site-packages/bam2plot/main.py", line 109, in <module>
    def coverage_for_many_values(df: pd.DataFrame, values: list[int]) -> pd.DataFrame:
TypeError: 'type' object is not subscriptable

Does anyone have the same issue?

Best regards,
Jing

**Comment by marcelglueck** [comment]
I stumbled upon this some time ago as well. This is not a bug per se. It is because you might be using a non-supported Python version. To my knowledge, bam2plot requires Python 3.9+. After upgrading my system to Python 3.10+, the program worked just fine for me.

**Comment by jing-rstbio** [comment]
Thanks for the comments. I update my python to 3.9, looks this problem fixed.
but I have another error: 
Traceback (most recent call last):
  File "/home/jing/.local/bin/bam2plot", line 5, in <module>
    from bam2plot.main import run
ModuleNotFoundError: No module named 'bam2plot'

I checked line 5, that is not this command.
Any suggestions on this?
Thanks in advance.
Jing

**Comment by willros** [comment]
@jing-rstbio 
Sorry for late reply. Did you manage to fix it?
