### ISSUE TITLE
zooming in on region

### ISSUE THREAD

**Issue by sparthib** [willros/bam2plot#3]
Hi there, 

is there a way to plot coverage for certain regions of a chromosome using bam2plot?

Thanks!
Sowmya

**Comment by willros** [comment]
Hi @sparthib!

Can you explain a little bit closer what you mean? I don't quite understand. 

Thanks!

**Comment by willros** [comment]
I added a functionality; "--zoom". Look in the new description.

Cheers

**Comment by sparthib** [comment]
Thank you for your very quick response!
