### ISSUE TITLE
Suggestion - genome-wide percent bases above X coverage

### ISSUE THREAD

**Issue by ghost** [willros/bam2plot#4]
Hello,

First of all, thank you for creating this package! I have used it, no bugs or errors, and it has been extremely useful for me.

I have a suggestion: would it be possible to have (as an echo while running, or as an output file, or whatever other way) a line on genome-wide percent bases above X coverage - like there is in every plot for each chromosome/contig, but cumulative, using the entirety of the reference genome?

I understand plotting it would be impossible, but was wondering if it would be easy to calculate it and output just a percentage.

Thank you very much in advance,

Valéria Marques

**Comment by willros** [comment]
Hi @vscmarques! 

Thank you for your suggestion.

So, if I understand you correctly, you want to have the coverage average for the reference genome as a whole? If the reference genome consisted of three chromosomes, you want the average for: sum(depth_total) / sum(bp_total)?
Thanks,
William

**Comment by willros** [comment]
I think I have added what you asked for now. Let me know if it works.

William

**Comment by ghost** [comment]
Hello William,

Thank you for the immediate response! And thank you for adding this feature to your already very useful package!

Cheers,

Valéria
