### ISSUE TITLE
--keep-zeros error on "perbase only-depth"

### ISSUE THREAD

**Issue by gabrluiz** [willros/bam2plot#9]
Hello,
 I was trying to use bam2plot, but I found the follow error: 
**Command 'perbase only-depth --keep-zeros bam2plot/test/barcode87.sorted.bam' returned non-zero exit status 1.**
 Based on my attempts, seems like "perbase only-depth" do not have  --keep-zeros parameter anymore.
Thank you for your attention,

**Comment by AnnaAntonatouPap** [comment]
hey, I have the same error, what was the solution for you ?  Thank you :)

**Comment by willros** [comment]
Hi!

bam2plot uses mosdepth under the hood nowadays, so use the latest version instead!
